development:
  adapter: postgresql
  database: upload_file_development
  pool: 5
  template: template0
  timeout: 5000
test:
  adapter: postgresql
  database: upload_file_test
  pool: 5
  template: template0
  timeout: 5000

production:
  adapter: postgresql
  database: upload_file_production
  pool: 5
  template: template0
  timeout: 5000